use_frameworks!

platform :ios, '8.0'

target 'XVIEWLocationManager_Example' do
  pod 'XVIEWLocationManager', :path => '../'

  target 'XVIEWLocationManager_Tests' do
    inherit! :search_paths

    
  end
end
